### ISSUE TITLE
Incompatible with aiohttp 3.8.3

### ISSUE THREAD

**Issue by dotlambda** [postlund/pyatv#1879]
### Describe the bug

After updating aiohttp to 3.8.3 the tests fail.

### Error log

```log
__________________ MrpAuthFunctionalTest.test_authentication ___________________

self = <mrp.test_mrp_auth.MrpAuthFunctionalTest testMethod=test_authentication>

    def setUp(self):
        AioHTTPTestCase.setUp(self)

        self.service = ManualService(
>           CLIENT_IDENTIFIER, Protocol.MRP, self.fake_atv.get_port(Protocol.MRP), {}
        )
E       AttributeError: 'MrpAuthFunctionalTest' object has no attribute 'fake_atv'

tests/protocols/mrp/test_mrp_auth.py:25: AttributeError
```

### How to reproduce the bug?

Install aiohttp 3.8.3 and run pytest.

### What is expected behavior?

No test failures.

### Operating System

Linux

### Python

3.10

### pyatv

0.10.3

### Device

x86_64

### Additional context

n/a

**Comment by postlund** [comment]
This is fixed since a while back now, thanks for reporting!
