### ISSUE TITLE
no remote. entity is created

### ISSUE THREAD

**Issue by spripe** [postlund/pyatv#521]
**Installed:** e9a6ac1
**HASS OS:** Home Assistant 0.106.6
**Hardware:** RPI4

I have problem that no Entity is created for the remote. Entity for the media_player is created for my AppleTv tvOS13 device.

**home-assistant.log says;**
2020-03-20 20:49:52 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Vardagsrum for remote
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 214, in async_setup
    result = await component.async_setup_entry(  # type: ignore
AttributeError: module 'homeassistant.components.remote' has no attribute 'async_setup_entry'

**Comment by postlund** [comment]
You need home Assistant 0.107.

**Comment by spripe** [comment]
Do you have any older version that works with versions prior to 0.107?
I've been told to waith to upgrae to 0.107 due to Other addons like custom header isn't working there yet.

**Comment by postlund** [comment]
Unfortunately no. I always prioritize the latest version to give myself less overhead in maintaining old stuff.

**Comment by spripe** [comment]
I agree, Thanks anyway, I'll wait a bit upgrading to 0.107
